version: '3'
services: 
    db:
        build: .
        container_name: "pg_container"
        environment: 
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=dados_financeiros
        ports: 
            - "5432:5432"  
        volumes: 
            - ./data:/var/lib/postgresql/data/
            
    bi:
        image: metabase/metabase
        restart: always
        ports: 
            - "3000:3000"
        volumes: 
            - ./metabase:/metabase-data  
        links: 
            - db
    
    jenkins:
        image: jenkins/jenkins:lts
        container_name: my-jenkins-3
        privileged: true
        user: root
        ports:
            - 8083:8080
            - 50003:50000
        volumes:
            - ./jenkins_data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock           
